{
 "title": "Все метрики",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Airflow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Статусты всех дагов",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "airflow_ti_status{state=~\"start|successes|finish\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Время длительности дагов",
     "type": "stat",
     "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(airflow_dagrun_duration{quantile=\"0.5\"}[$__interval])",
       "legendFormat": "{{dag_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Всего воркеров",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "metrics_master_workers_Number", "legendFormat": "Всего воркеров" },
      {
       "expr": "metrics_master_aliveWorkers_Number",
       "legendFormat": "Живые воркеры"
      }
     ]
    },
    {
     "title": " Занятая память",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "metrics_worker_memUsed_MB_Number",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Занятые ядра процессора",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "metrics_worker_coresUsed_Number",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hadoop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Занято под HDFS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hadoop_namenode_capacityused{name=\"FSNamesystem\"}",
       "legendFormat": "Занято под HDFS"
      }
     ]
    },
    {
     "title": "Всего папок и файлов",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hadoop_namenode_filestotal{name=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Размер",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (pg_database_size_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Доступность",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 51 },
     "targets": [
      { "expr": "pg_up", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Всего подключений",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum by(instance) (pg_stat_activity_count)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}