services:
  nlp:
    build: ../../NLP
    container_name: nlp
    env_file:
      - .env
    ports:
      - "127.0.0.1:15000:5000"
    volumes:
      - ../../NLP/thresholds.json:/app/thresholds.json
      - nlp-hf-cache:/cache/huggingface
    restart: unless-stopped
    networks:
      - data_platform_net
    depends_on:
      app-postgres:
        condition: service_healthy

volumes:
  nlp-hf-cache:
