services:
  app-postgres:
    image: postgres:17
    container_name: app-postgres
    ports:
      - "127.0.0.1:14432:5432"
    volumes:
      - app-postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASS:-1234}
      POSTGRES_DB: ${PG_DB:-vacstorage}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USER:-postgres}", "-d", "${PG_DB:-vacstorage}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - data_platform_net

  flyway:
    image: flyway/flyway:10
    container_name: flyway
    command: -connectRetries=10 migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://app-postgres:5432/${PG_DB:-vacstorage}
      FLYWAY_USER: ${PG_USER:-postgres}
      FLYWAY_PASSWORD: ${PG_PASS:-1234}
    volumes:
      - ../../dataBase/DWH:/flyway/sql
    restart: on-failure
    networks:
      - data_platform_net
    depends_on:
      app-postgres:
        condition: service_healthy

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${PG_USER:-postgres}:${PG_PASS:-1234}@app-postgres:5432/${PG_DB:-vacstorage}?sslmode=disable"
    restart: unless-stopped
    networks:
      - data_platform_net
    depends_on:
      app-postgres:
        condition: service_healthy

volumes:
  app-postgres-db-volume: