services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9092:9090'
    volumes:
      - ./config/prometheus_conf.yml:/etc/prometheus/prometheus.yml
      - ../../prometheus/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  # airflow
  statsd-exporter:
    image: prom/statsd-exporter:v0.21.0
    volumes:
      - ./config/statsd.yml:/home/statsd-mapping-configs.yml
    entrypoint: ["/bin/sh", "-c", "--"]
    command: ["statsd_exporter --log.level debug --statsd.mapping-config=/home/statsd-mapping-configs.yml"]
    ports:
      - "9102:9102"
      - "9125:9125"