services:  
  superset:
    build: .
    container_name: superset
    ports:
      - "16088:8088"
    volumes:
      - superset-volume:/app/superset_data
      - ../../superset:/superset-mount
    environment:
      - SUPERSET_CONFIG_PATH=/superset-mount/conf/superset_config.py
    command: [ "/bin/bash", "/superset-mount/conf/start-superset.sh" ]
    depends_on:
      superset-postgres:
        condition: service_healthy

  superset-postgres:
    image: postgres:17
    container_name: superset-postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "effective_cache_size=256MB"
      - "-c"
      - "work_mem=8MB"
    volumes:
      - superset-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "superset", "-d", "superset"]
      interval: 10s
      retries: 5
      start_period: 5s

  grafana:
    image: grafana/grafana-enterprise:11.6.1
    container_name: grafana
    ports:
      - "16000:3000"
    volumes:
      - ../../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../../grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ../../grafana/dashboards-json:/var/lib/grafana/dashboards
      - grafana-volume:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

volumes:
  superset-volume:
  superset-postgres-volume:
  grafana-volume: