services:
  superset:
    build: .
    container_name: superset
    ports:
      - "127.0.0.1:16088:8088"
    volumes:
      - superset-volume:/app/superset_data
      - ../../superset:/superset-mount
    environment:
      SUPERSET_CONFIG_PATH: /superset-mount/conf/superset_config.py
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY:-thisISaSECRET_1234}
      SUPERSET_DB_URI: postgresql+psycopg2://${SUPERSET_PG_USER:-superset}:${SUPERSET_PG_PASSWORD:-superset}@superset-postgres:5432/${SUPERSET_PG_DB:-superset}
      MAPBOX_API_KEY: ${MAPBOX_API_KEY:-}
      SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME:-admin}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD:-admin}
      SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME:-Admin}
      SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME:-User}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL:-admin@superset.local}
    command: ["/bin/bash", "/superset-mount/conf/start-superset.sh"]
    restart: unless-stopped
    networks:
      - data_platform_net
    depends_on:
      superset-postgres:
        condition: service_healthy

  superset-postgres:
    image: postgres:17
    container_name: superset-postgres
    environment:
      POSTGRES_USER: ${SUPERSET_PG_USER:-superset}
      POSTGRES_PASSWORD: ${SUPERSET_PG_PASSWORD:-superset}
      POSTGRES_DB: ${SUPERSET_PG_DB:-superset}
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "effective_cache_size=256MB"
      - "-c"
      - "work_mem=8MB"
    volumes:
      - superset-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SUPERSET_PG_USER:-superset}", "-d", "${SUPERSET_PG_DB:-superset}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - data_platform_net

  grafana:
    image: grafana/grafana-enterprise:11.6.1
    container_name: grafana
    ports:
      - "127.0.0.1:16000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL:-http://localhost:3000}
      GF_SERVER_DOMAIN: ${GF_SERVER_DOMAIN:-localhost}
      GF_SECURITY_CSRF_TRUSTED_ORIGINS: ${GF_SECURITY_CSRF_TRUSTED_ORIGINS}
    volumes:
      - ../../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../../grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ../../grafana/dashboards-json:/var/lib/grafana/dashboards
      - grafana-volume:/var/lib/grafana
    restart: unless-stopped
    networks:
      - data_platform_net
    depends_on:
      - prometheus

volumes:
  superset-volume:
  superset-postgres-volume:
  grafana-volume: