DataBase {
    host = "app-postgres"
    port = "5432"
    baseName = "vacstorage"
    userName = "postgres"
    userPassword = "1234"

    maxPartitions = 5
    batchSize = 3000
}

FileSystem {
    url = "hdfs://namenode:9000"
    path = "VacStorage"
    
    platform = "unknown"
}

Spark {
    name = "SparkApp"
    master = "spark://spark-master:7077"
    driverMemory = "1g"
    driverCores = "1"
    executorMemory = "10g"
    executorCores = "10"
}

Network {
    headers {
        User-Agent = "Aggregator App"
    }

    requestsPerSecond = 30
    timeout = 5000 # ms
}

FuzzyMatcher {
    default {
        minScoreThreshold = 0.85
        numberPenalty = 0.6
        ngramWeight = 0.6
        levenshteinWeight = 0.4
        ngramSize = 3
    }

    employer {
        ngramWeight = 0.75
        levenshteinWeight = 0.35
        minScoreThreshold = 0.7
    }

    _strict_dict {
        ngramWeight = 0.3
        levenshteinWeight = 0.7
        minScoreThreshold = 0.85
        ngramSize = 2
    }

    currency = ${FuzzyMatcher._strict_dict}
    schedules = ${FuzzyMatcher._strict_dict}
    employments = ${FuzzyMatcher._strict_dict}
    platform = ${FuzzyMatcher._strict_dict}


    _tech_dict {
        numberPenalty = 1.0
        ngramWeight = 0.5
        levenshteinWeight = 0.5
        minScoreThreshold = 0.85
        ngramSize = 2
    }

    skills = ${FuzzyMatcher._tech_dict}
    experience = ${FuzzyMatcher._tech_dict}
    languages_level = ${FuzzyMatcher._tech_dict}
    grades = ${FuzzyMatcher._tech_dict}


    _location_dict {
        numberPenalty = 0.1
        ngramWeight = 0.4
        levenshteinWeight = 0.6
        minScoreThreshold = 0.85
    }

    locations = ${FuzzyMatcher._location_dict}
    country = ${FuzzyMatcher._location_dict}
}

Arguments {
    rawPartitions = 1
    
    updateLimit = 5000
}

Dags {
    ETL {
        fileName = "{{ ds }}"
    }

    RefreshMatViews {
        schedule = "" # 0 18 * * *
    }

    DeleteData {
        schedule = "0 19 1 * *"

        rawData = 60
        transformedData = 60
    }
}
