include "common.conf"

Arguments {
    apiKey = ""
    apiBaseUrl = "https://v6.exchangerate-api.com/v6"
}

FileSystem {
    platform = "Exchangerate"
}

Dags {
    ETL {
        schedule = "0 13 * * *"
    }
}

include "local_exchangerate.conf"