include "common.conf"

Arguments {
    vacsPageLimit = 100
    vacsPerPage = 50 # <= 50

    apiBaseUrl = "https://career.habr.com/api"
}

FileSystem {
    platform = "HabrCareer"
}

Dags {
    ETL {
        schedule = "" # 0 14 * * *
    }
}