include "common.conf"

Arguments {
    fieldIds = [11] # https://api.hh.ru/professional_roles
    vacsPerPage = 100 # <= 100
    pageLimit = 19 # <= 19

    apiBaseUrl = "https://api.hh.ru"
}

FileSystem {
    platform = "HeadHunter"
}

Dags {

    ETL {
        schedule = "" # 0 10 * * * 
        fileName = "{{ logical_date.strftime('%Y-%m-%dT%H') }}"
        dateFrom = "{{ (logical_date - macros.timedelta(hours=48)).strftime('%Y-%m-%dT%H:%M:%SZ') }}"
    }
}

include "local_hh.conf"