SECRET_KEY = 'YOUR_SECRET_KEY'
MAPBOX_API_KEY = 'MAPBOX_API_KEY'

ENABLE_JAVASCRIPT_CONTROLS = True
HTML_SANITIZATION = False
TALISMAN_ENABLED = False

FEATURE_FLAGS = {
    'ENABLE_TEMPLATE_PROCESSING': True,
    'DASHBOARD_NATIVE_FILTERS': True,
    'DASHBOARD_CROSS_FILTERS': True,
}