SECRET_KEY = 'nhgH0yelqENg+jgNw9I16VLdFF3P206ciSsOyyM3ng4sPG1m2UUxqrNi'
MAPBOX_API_KEY = 'YOUR_API_KEY'

ENABLE_JAVASCRIPT_CONTROLS = True
HTML_SANITIZATION = False
TALISMAN_ENABLED = False

FEATURE_FLAGS = {
    'ENABLE_TEMPLATE_PROCESSING': True,
    'DASHBOARD_NATIVE_FILTERS': True,
    'DASHBOARD_CROSS_FILTERS': True,
}