include "../base/base.conf"

FileSystem {
    platform = "GeekJob"
}

Arguments {
    pageLimit  = 20

    apiBaseUrl = "https://geekjob.ru"
}

Dags {
    ETL {
        schedule = "0 6 * * *"
    }
}
