include "../base/base.conf"

FileSystem {
    platform = "GeekJob"
}

Arguments {
    pageLimit  = 50

    apiBaseUrl = "https://geekjob.ru"
}

Dags {
    ETL {
        schedule = ""  # 0 4 * * *
    }
}
