include "base/base.conf"

FileSystem {
    platform = "HabrCareer"
}

Arguments {
    vacsPageLimit = 100
    vacsPerPage   = 50  # <= 50

    apiBaseUrl = "https://career.habr.com/api"
}

Dags {
    ETL {
        schedule = ""  # 0 14 * * *
    }
}
