_FuzzyTemplates {
    _strict {
        ngramWeight       = 0.3
        levenshteinWeight = 0.7
        minScoreThreshold = 0.85
        ngramSize         = 2
    }
    _tech {
        numberPenalty     = 1.0
        ngramWeight       = 0.5
        levenshteinWeight = 0.5
        minScoreThreshold = 0.85
        ngramSize         = 2
    }
    _location {
        numberPenalty     = 0.1
        ngramWeight       = 0.4
        levenshteinWeight = 0.6
        minScoreThreshold = 0.85
    }
}

FuzzyMatcher {
    default {
        minScoreThreshold = 0.85
        numberPenalty     = 0.6
        ngramWeight       = 0.6
        levenshteinWeight = 0.4
        ngramSize         = 3
    }

    employer {
        ngramWeight       = 0.75
        levenshteinWeight = 0.35
        minScoreThreshold = 0.7
    }


    currency    = ${_FuzzyTemplates._strict}
    schedules   = ${_FuzzyTemplates._strict}
    employments = ${_FuzzyTemplates._strict}
    platform    = ${_FuzzyTemplates._strict}


    skills          = ${_FuzzyTemplates._tech}
    experience      = ${_FuzzyTemplates._tech}
    languages_level = ${_FuzzyTemplates._tech}
    grades          = ${_FuzzyTemplates._tech}


    locations = ${_FuzzyTemplates._location}
    country   = ${_FuzzyTemplates._location}
}
