include "secrets/local_airflow.conf"

FileSystem {
    path = "VacStorage"
}

Dags {
    RefreshMatViews {
        schedule = ""  # 0 18 * * *
    }

    DeleteData {
        schedule = ""  # 0 19 1 * *
        rawData  = 2
    }
}